"""initial schema - 14 tables

Revision ID: bf32b91cf811
Revises: 
Create Date: 2026-05-19 14:15:42.178041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf32b91cf811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_hash', sa.Text(), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_hash')
    )
    op.create_index('idx_plan_cache_hash', 'plan_cache', ['quiz_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('program_day', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('plan_start_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('baseline_photo_url', sa.Text(), nullable=True),
    sa.Column('baseline_photo_path', sa.Text(), nullable=True),
    sa.Column('face_shape', sa.Text(), nullable=True),
    sa.Column('referral_code', sa.Text(), nullable=True),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('first_strike_completed', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.Text(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_provider', sa.Text(), nullable=False),
    sa.Column('initial_compliment', sa.Text(), nullable=True),
    sa.CheckConstraint('name IS NULL OR LENGTH(name) BETWEEN 1 AND 100', name='ck_users_name_length'),
    sa.CheckConstraint('season >= 1 AND season <= 99', name='ck_users_season_range'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.Text(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_achievements_user_badge')
    )
    op.create_table('challenge_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('progress >= 0', name='ck_challenge_progress_positive'),
    sa.CheckConstraint('target > 0', name='ck_challenge_target_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('cycle_type', sa.Text(), nullable=False),
    sa.Column('face_shape', sa.Text(), nullable=True),
    sa.Column('facial_composition_score', sa.Integer(), nullable=True),
    sa.Column('skin_score', sa.Integer(), nullable=True),
    sa.Column('grooming_score', sa.Integer(), nullable=True),
    sa.Column('hair_score', sa.Integer(), nullable=True),
    sa.Column('posture_score', sa.Integer(), nullable=True),
    sa.Column('style_score', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('nutrition_score', sa.Integer(), nullable=True),
    sa.Column('voice_score', sa.Integer(), nullable=True),
    sa.Column('ai_insight', sa.Text(), nullable=True),
    sa.Column('next_focus', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('facial_composition_score IS NULL OR facial_composition_score BETWEEN 0 AND 100', name='ck_cycles_facial'),
    sa.CheckConstraint('grooming_score IS NULL OR grooming_score BETWEEN 0 AND 100', name='ck_cycles_grooming'),
    sa.CheckConstraint('hair_score IS NULL OR hair_score BETWEEN 0 AND 100', name='ck_cycles_hair'),
    sa.CheckConstraint('nutrition_score IS NULL OR nutrition_score BETWEEN 0 AND 100', name='ck_cycles_nutrition'),
    sa.CheckConstraint('posture_score IS NULL OR posture_score BETWEEN 0 AND 100', name='ck_cycles_posture'),
    sa.CheckConstraint('skin_score IS NULL OR skin_score BETWEEN 0 AND 100', name='ck_cycles_skin'),
    sa.CheckConstraint('sleep_score IS NULL OR sleep_score BETWEEN 0 AND 100', name='ck_cycles_sleep'),
    sa.CheckConstraint('style_score IS NULL OR style_score BETWEEN 0 AND 100', name='ck_cycles_style'),
    sa.CheckConstraint('voice_score IS NULL OR voice_score BETWEEN 0 AND 100', name='ck_cycles_voice'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cycle_number', name='uq_cycles_user_number')
    )
    op.create_index('idx_cycles_user_type', 'cycles', ['user_id', 'cycle_type'], unique=False)
    op.create_table('micro_sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sprint_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_task_effects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('pillar', sa.Text(), nullable=False),
    sa.Column('drift', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=True),
    sa.Column('focus_summary', sa.Text(), nullable=True),
    sa.Column('honest_expectation', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('facial_composition_score', sa.Integer(), nullable=False),
    sa.Column('skin_score', sa.Integer(), nullable=False),
    sa.Column('grooming_score', sa.Integer(), nullable=False),
    sa.Column('hair_score', sa.Integer(), nullable=False),
    sa.Column('posture_score', sa.Integer(), nullable=False),
    sa.Column('style_score', sa.Integer(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('nutrition_score', sa.Integer(), nullable=False),
    sa.Column('voice_score', sa.Integer(), nullable=False),
    sa.Column('optimisation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_streak >= 0', name='ck_progress_streak_positive'),
    sa.CheckConstraint('facial_composition_score BETWEEN 0 AND 100', name='ck_progress_facial'),
    sa.CheckConstraint('grooming_score BETWEEN 0 AND 100', name='ck_progress_grooming'),
    sa.CheckConstraint('hair_score BETWEEN 0 AND 100', name='ck_progress_hair'),
    sa.CheckConstraint('longest_streak >= 0', name='ck_progress_longest_positive'),
    sa.CheckConstraint('nutrition_score BETWEEN 0 AND 100', name='ck_progress_nutrition'),
    sa.CheckConstraint('optimisation_score BETWEEN 0 AND 100', name='ck_progress_optimisation'),
    sa.CheckConstraint('posture_score BETWEEN 0 AND 100', name='ck_progress_posture'),
    sa.CheckConstraint('skin_score BETWEEN 0 AND 100', name='ck_progress_skin'),
    sa.CheckConstraint('sleep_score BETWEEN 0 AND 100', name='ck_progress_sleep'),
    sa.CheckConstraint('style_score BETWEEN 0 AND 100', name='ck_progress_style'),
    sa.CheckConstraint('total_xp >= 0', name='ck_progress_xp_positive'),
    sa.CheckConstraint('voice_score BETWEEN 0 AND 100', name='ck_progress_voice'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goals', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('routine_level', sa.Text(), nullable=True),
    sa.Column('daily_time', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('main_concern', sa.Text(), nullable=True),
    sa.Column('age_range', sa.Text(), nullable=True),
    sa.Column('has_photo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('from_season', sa.Integer(), nullable=False),
    sa.Column('to_season', sa.Integer(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_season_events_user_created', 'season_events', ['user_id', 'created_at'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('why_it_works', sa.Text(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('xp_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('library_task_id', sa.Text(), nullable=True),
    sa.Column('pillar', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_number >= 1', name='ck_daily_tasks_day_positive'),
    sa.CheckConstraint('xp_value >= 0', name='ck_daily_tasks_xp_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_tasks_user_day', 'daily_tasks', ['user_id', 'day_number'], unique=False)
    op.create_index('idx_daily_tasks_week_pillar', 'daily_tasks', ['user_id', 'week_number', 'pillar'], unique=False)
    op.create_table('task_library_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('library_task_id', sa.Text(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_library_selections')
    op.drop_index('idx_daily_tasks_week_pillar', table_name='daily_tasks')
    op.drop_index('idx_daily_tasks_user_day', table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_table('weekly_reports')
    op.drop_index('idx_season_events_user_created', table_name='season_events')
    op.drop_table('season_events')
    op.drop_table('quiz_answers')
    op.drop_table('progress')
    op.drop_table('plans')
    op.drop_table('pending_task_effects')
    op.drop_table('micro_sprints')
    op.drop_index('idx_cycles_user_type', table_name='cycles')
    op.drop_table('cycles')
    op.drop_table('challenge_progress')
    op.drop_table('achievements')
    op.drop_table('users')
    op.drop_index('idx_plan_cache_hash', table_name='plan_cache')
    op.drop_table('plan_cache')
    # ### end Alembic commands ###
