"""Curated task library for FORGE plan generation.

~150 tasks organized by pillar and tier.
Each task has: id, title, category (pillar), tier, duration_mins, why_it_works, xp_value.
The plan generator selects from this library based on quiz answers.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class LibraryTask:
    id: str
    title: str
    category: str
    tier: str
    duration_mins: int
    why_it_works: str
    xp_value: int = 10


TASK_LIBRARY: list[LibraryTask] = [
    # =========================================================================
    # SKIN (18 tasks)
    # =========================================================================
    LibraryTask(
        "skin-b-01",
        "Gentle cleanser wash (AM)",
        "skin",
        "beginner",
        3,
        "Removes overnight sebum without stripping moisture barrier.",
    ),
    LibraryTask(
        "skin-b-02",
        "Apply SPF 30+ sunscreen",
        "skin",
        "beginner",
        2,
        "UV protection prevents 80% of visible skin ageing.",
    ),
    LibraryTask(
        "skin-b-03",
        "Basic moisturiser application",
        "skin",
        "beginner",
        2,
        "Maintains hydration and reinforces the skin barrier.",
    ),
    LibraryTask(
        "skin-b-04",
        "Gentle cleanser wash (PM)",
        "skin",
        "beginner",
        3,
        "Removes daily pollutants and prevents pore congestion.",
    ),
    LibraryTask(
        "skin-b-05",
        "Drink 2L water throughout the day",
        "skin",
        "beginner",
        1,
        "Systemic hydration supports skin turgor and clarity.",
    ),
    LibraryTask(
        "skin-b-06",
        "Change pillowcase",
        "skin",
        "beginner",
        2,
        "Reduces bacterial transfer to facial skin during sleep.",
    ),
    LibraryTask(
        "skin-i-01",
        "Apply niacinamide serum",
        "skin",
        "intermediate",
        2,
        "Regulates sebum, minimises pores, and evens tone.",
    ),
    LibraryTask(
        "skin-i-02",
        "Hyaluronic acid serum on damp skin",
        "skin",
        "intermediate",
        2,
        "Draws moisture into the epidermis for plumper skin.",
    ),
    LibraryTask(
        "skin-i-03",
        "Chemical exfoliant (BHA/AHA) 2x/week",
        "skin",
        "intermediate",
        3,
        "Dissolves dead cells and unclogs pores chemically.",
    ),
    LibraryTask(
        "skin-i-04",
        "Sheet mask hydration session",
        "skin",
        "intermediate",
        15,
        "Intensive hydration boosts glow for 24-48 hours.",
    ),
    LibraryTask(
        "skin-i-05",
        "Apply vitamin C serum (AM)",
        "skin",
        "intermediate",
        2,
        "Antioxidant protection and collagen synthesis support.",
    ),
    LibraryTask(
        "skin-i-06",
        "Ice roller facial massage",
        "skin",
        "intermediate",
        5,
        "Reduces puffiness and constricts blood vessels for tighter look.",
    ),
    LibraryTask(
        "skin-a-01",
        "Retinoid application (PM)",
        "skin",
        "advanced",
        2,
        "Accelerates cell turnover by binding RAR receptors.",
    ),
    LibraryTask(
        "skin-a-02",
        "Double cleansing routine",
        "skin",
        "advanced",
        5,
        "Oil cleanser dissolves sunscreen; water cleanser removes residue.",
    ),
    LibraryTask(
        "skin-a-03",
        "Microneedling session (monthly)",
        "skin",
        "advanced",
        20,
        "Triggers collagen remodelling through controlled micro-injury.",
    ),
    LibraryTask(
        "skin-a-04",
        "LED red light therapy (10 min)",
        "skin",
        "advanced",
        10,
        "660nm wavelength stimulates fibroblast collagen production.",
    ),
    LibraryTask(
        "skin-a-05",
        "Peptide serum application",
        "skin",
        "advanced",
        2,
        "Signal peptides stimulate collagen and elastin synthesis.",
    ),
    LibraryTask(
        "skin-a-06",
        "Gua sha facial sculpting",
        "skin",
        "advanced",
        10,
        "Promotes lymphatic drainage and reduces facial tension.",
    ),
    # =========================================================================
    # HAIR (16 tasks)
    # =========================================================================
    LibraryTask(
        "hair-b-01",
        "Shampoo with sulphate-free wash",
        "hair",
        "beginner",
        5,
        "Cleans without stripping natural oils that protect the cuticle.",
    ),
    LibraryTask(
        "hair-b-02",
        "Apply conditioner to ends",
        "hair",
        "beginner",
        3,
        "Seals the cuticle and prevents split ends and breakage.",
    ),
    LibraryTask(
        "hair-b-03",
        "Towel dry gently (no rubbing)",
        "hair",
        "beginner",
        2,
        "Reduces friction damage to wet, vulnerable hair strands.",
    ),
    LibraryTask(
        "hair-b-04",
        "Comb with wide-tooth comb",
        "hair",
        "beginner",
        2,
        "Detangles without snapping strands or pulling follicles.",
    ),
    LibraryTask(
        "hair-b-05",
        "Research a hairstyle for your face shape",
        "hair",
        "beginner",
        10,
        "The right cut creates visual balance for facial proportions.",
    ),
    LibraryTask(
        "hair-i-01",
        "Apply leave-in conditioner",
        "hair",
        "intermediate",
        2,
        "Ongoing moisture protection between washes.",
    ),
    LibraryTask(
        "hair-i-02",
        "Scalp massage (5 min)",
        "hair",
        "intermediate",
        5,
        "Increases blood flow to follicles, promoting growth.",
    ),
    LibraryTask(
        "hair-i-03",
        "Style with matte product",
        "hair",
        "intermediate",
        5,
        "Adds texture and hold without greasy appearance.",
    ),
    LibraryTask(
        "hair-i-04",
        "Cold water final rinse",
        "hair",
        "intermediate",
        1,
        "Closes the cuticle for smoother, shinier hair.",
    ),
    LibraryTask(
        "hair-i-05",
        "Apply hair oil to damp hair",
        "hair",
        "intermediate",
        2,
        "Locks in moisture and adds shine without weight.",
    ),
    LibraryTask(
        "hair-a-01",
        "Biotin supplement (daily)",
        "hair",
        "advanced",
        1,
        "Supports keratin infrastructure for stronger strands.",
    ),
    LibraryTask(
        "hair-a-02",
        "Ketoconazole shampoo (2x/week)",
        "hair",
        "advanced",
        5,
        "Anti-fungal reduces DHT at the scalp for hair preservation.",
    ),
    LibraryTask(
        "hair-a-03",
        "Apply minoxidil (if prescribed)",
        "hair",
        "advanced",
        2,
        "Vasodilator extends anagen phase for thicker growth.",
    ),
    LibraryTask(
        "hair-a-04",
        "Deep conditioning mask (weekly)",
        "hair",
        "advanced",
        20,
        "Intensive repair of protein bonds in damaged hair.",
    ),
    LibraryTask(
        "hair-a-05",
        "Blow dry with heat protectant",
        "hair",
        "advanced",
        10,
        "Controlled styling with minimal thermal damage.",
    ),
    LibraryTask(
        "hair-a-06",
        "Derma roller on scalp (weekly)",
        "hair",
        "advanced",
        10,
        "Microneedling stimulates dormant follicles via growth factors.",
    ),
    # =========================================================================
    # GROOMING (16 tasks)
    # =========================================================================
    LibraryTask(
        "groom-b-01",
        "Trim nose and ear hair",
        "grooming",
        "beginner",
        5,
        "Clean lines improve perceived grooming effort instantly.",
    ),
    LibraryTask(
        "groom-b-02",
        "Shape eyebrows (remove strays)",
        "grooming",
        "beginner",
        5,
        "Defined brows frame the eyes and structure the face.",
    ),
    LibraryTask(
        "groom-b-03",
        "Clean and file nails",
        "grooming",
        "beginner",
        5,
        "Well-kept nails signal attention to detail.",
    ),
    LibraryTask(
        "groom-b-04",
        "Brush teeth (2 min, twice daily)",
        "grooming",
        "beginner",
        4,
        "Removes plaque and maintains enamel and gum health.",
    ),
    LibraryTask(
        "groom-b-05",
        "Floss before bed",
        "grooming",
        "beginner",
        3,
        "Removes interdental plaque that brushing misses.",
    ),
    LibraryTask(
        "groom-b-06",
        "Apply lip balm with SPF",
        "grooming",
        "beginner",
        1,
        "Prevents chapping and UV damage to thin lip skin.",
    ),
    LibraryTask(
        "groom-i-01",
        "Beard/stubble trim and shape",
        "grooming",
        "intermediate",
        10,
        "Defined jaw and necklines sharpen facial structure.",
    ),
    LibraryTask(
        "groom-i-02",
        "Apply beard oil",
        "grooming",
        "intermediate",
        2,
        "Moisturises underlying skin and softens beard hair.",
    ),
    LibraryTask(
        "groom-i-03",
        "Tongue scraping",
        "grooming",
        "intermediate",
        2,
        "Removes bacteria that cause bad breath at the source.",
    ),
    LibraryTask(
        "groom-i-04",
        "Whitening strips or charcoal treatment",
        "grooming",
        "intermediate",
        15,
        "Removes surface stains for a brighter smile.",
    ),
    LibraryTask(
        "groom-i-05",
        "Apply hand cream",
        "grooming",
        "intermediate",
        1,
        "Keeps hands presentable — one of the most noticed body parts.",
    ),
    LibraryTask(
        "groom-a-01",
        "Professional beard lineup (monthly)",
        "grooming",
        "advanced",
        30,
        "Barber precision creates architectural facial framing.",
    ),
    LibraryTask(
        "groom-a-02",
        "Teeth whitening kit session",
        "grooming",
        "advanced",
        20,
        "Peroxide-based treatment brightens by multiple shades.",
    ),
    LibraryTask(
        "groom-a-03",
        "Cologne application (pulse points)",
        "grooming",
        "advanced",
        2,
        "Scent completes the grooming impression from a distance.",
    ),
    LibraryTask(
        "groom-a-04",
        "Cuticle care and hand mask",
        "grooming",
        "advanced",
        15,
        "Detail grooming elevates overall polished appearance.",
    ),
    LibraryTask(
        "groom-a-05",
        "Facial hair detail razor work",
        "grooming",
        "advanced",
        10,
        "Precision edging creates sharp, intentional lines.",
    ),
    # =========================================================================
    # FACIAL COMPOSITION (14 tasks)
    # =========================================================================
    LibraryTask(
        "face-b-01",
        "Mewing: tongue posture practice (5 min)",
        "facial_composition",
        "beginner",
        5,
        "Proper tongue posture supports forward facial development.",
    ),
    LibraryTask(
        "face-b-02",
        "Jaw relaxation exercises",
        "facial_composition",
        "beginner",
        5,
        "Releases TMJ tension that causes asymmetry and pain.",
    ),
    LibraryTask(
        "face-b-03",
        "Chew gum (sugar-free, 15 min)",
        "facial_composition",
        "beginner",
        15,
        "Builds masseter muscle for a more defined jawline.",
    ),
    LibraryTask(
        "face-b-04",
        "Face yoga: cheek lifts",
        "facial_composition",
        "beginner",
        5,
        "Tones mid-face muscles for a lifted appearance.",
    ),
    LibraryTask(
        "face-i-01",
        "Jawline resistance exercise",
        "facial_composition",
        "intermediate",
        10,
        "Progressive resistance strengthens the jaw muscles.",
    ),
    LibraryTask(
        "face-i-02",
        "Facial symmetry assessment (mirror)",
        "facial_composition",
        "intermediate",
        5,
        "Awareness of imbalances guides targeted exercises.",
    ),
    LibraryTask(
        "face-i-03",
        "Neck curl exercises (3 sets)",
        "facial_composition",
        "intermediate",
        10,
        "Strengthens sternocleidomastoid for a defined neck-jaw angle.",
    ),
    LibraryTask(
        "face-i-04",
        "Cold water face immersion",
        "facial_composition",
        "intermediate",
        3,
        "Reduces inflammation and tightens facial skin temporarily.",
    ),
    LibraryTask(
        "face-i-05",
        "Hard food diet day (raw veg, nuts)",
        "facial_composition",
        "intermediate",
        1,
        "Natural chewing resistance develops masticatory muscles.",
    ),
    LibraryTask(
        "face-a-01",
        "Jaw exerciser tool workout",
        "facial_composition",
        "advanced",
        15,
        "Calibrated resistance tool maximises masseter hypertrophy.",
    ),
    LibraryTask(
        "face-a-02",
        "Mewing with hard swallow practice",
        "facial_composition",
        "advanced",
        10,
        "Advanced mewing technique for palate expansion.",
    ),
    LibraryTask(
        "face-a-03",
        "Buccal fat reduction exercises",
        "facial_composition",
        "advanced",
        10,
        "Cheek hollowing exercises for more sculpted appearance.",
    ),
    LibraryTask(
        "face-a-04",
        "Facial muscle mapping exercise",
        "facial_composition",
        "advanced",
        15,
        "Targeted isolation of 43 facial muscles for balanced tone.",
    ),
    LibraryTask(
        "face-a-05",
        "Bone-pressing technique (advanced)",
        "facial_composition",
        "advanced",
        10,
        "Controversial but practiced: sustained pressure for remodelling.",
    ),
    # =========================================================================
    # POSTURE (16 tasks)
    # =========================================================================
    LibraryTask(
        "post-b-01",
        "Wall angel stretch (10 reps)",
        "posture",
        "beginner",
        5,
        "Opens the chest and retrains scapular positioning.",
    ),
    LibraryTask(
        "post-b-02",
        "Chin tucks (3 sets of 10)",
        "posture",
        "beginner",
        5,
        "Corrects forward head posture by strengthening deep neck flexors.",
    ),
    LibraryTask(
        "post-b-03",
        "Desk posture check (hourly alarm)",
        "posture",
        "beginner",
        1,
        "Frequent cues prevent sustained slouching patterns.",
    ),
    LibraryTask(
        "post-b-04",
        "Cat-cow spine mobility (5 min)",
        "posture",
        "beginner",
        5,
        "Restores thoracic mobility lost from sitting.",
    ),
    LibraryTask(
        "post-b-05",
        "Doorway chest stretch (2 min)",
        "posture",
        "beginner",
        2,
        "Lengthens pectoralis minor that pulls shoulders forward.",
    ),
    LibraryTask(
        "post-i-01",
        "Thoracic extension on foam roller",
        "posture",
        "intermediate",
        5,
        "Mobilises stiff T-spine segments for upright carriage.",
    ),
    LibraryTask(
        "post-i-02",
        "Band pull-aparts (3 x 15)",
        "posture",
        "intermediate",
        5,
        "Strengthens mid-traps and rhomboids for shoulder retraction.",
    ),
    LibraryTask(
        "post-i-03",
        "Dead hang (30-60 seconds)",
        "posture",
        "intermediate",
        2,
        "Decompresses spine and stretches lats and shoulders.",
    ),
    LibraryTask(
        "post-i-04",
        "Standing desk intervals (30 min)",
        "posture",
        "intermediate",
        30,
        "Alternating sit-stand reduces sustained flexion loading.",
    ),
    LibraryTask(
        "post-i-05",
        "Glute bridge holds (3 x 30s)",
        "posture",
        "intermediate",
        5,
        "Activates glutes to counter anterior pelvic tilt.",
    ),
    LibraryTask(
        "post-a-01",
        "Face pulls with external rotation",
        "posture",
        "advanced",
        10,
        "Targets rear delts and rotator cuff for shoulder health.",
    ),
    LibraryTask(
        "post-a-02",
        "Turkish get-up practice",
        "posture",
        "advanced",
        15,
        "Full-body stabilisation builds postural endurance.",
    ),
    LibraryTask(
        "post-a-03",
        "Jefferson curl progression",
        "posture",
        "advanced",
        10,
        "Controlled spinal flexion under load builds segmental control.",
    ),
    LibraryTask(
        "post-a-04",
        "Overhead squat mobility work",
        "posture",
        "advanced",
        10,
        "Tests and improves full-chain postural integration.",
    ),
    LibraryTask(
        "post-a-05",
        "Farmers walk (heavy, 3 x 40m)",
        "posture",
        "advanced",
        10,
        "Loaded carry builds anti-lateral-flexion and upright posture.",
    ),
    LibraryTask(
        "post-a-06",
        "Yoga flow: warrior sequence",
        "posture",
        "advanced",
        15,
        "Integrated movement builds balance, strength, and alignment.",
    ),
    # =========================================================================
    # STYLE (16 tasks)
    # =========================================================================
    LibraryTask(
        "style-b-01",
        "Audit wardrobe: remove ill-fitting items",
        "style",
        "beginner",
        20,
        "Eliminating poor fits raises the floor of your daily outfit.",
    ),
    LibraryTask(
        "style-b-02",
        "Iron/steam outfit for tomorrow",
        "style",
        "beginner",
        10,
        "Crisp fabrics signal intentionality and care.",
    ),
    LibraryTask(
        "style-b-03",
        "Match belt and shoes colour",
        "style",
        "beginner",
        2,
        "Colour coordination creates visual coherence.",
    ),
    LibraryTask(
        "style-b-04",
        "Clean and condition leather shoes",
        "style",
        "beginner",
        10,
        "Well-maintained shoes elevate any outfit.",
    ),
    LibraryTask(
        "style-b-05",
        "Plan tomorrow's outfit tonight",
        "style",
        "beginner",
        5,
        "Eliminates morning decision fatigue and poor choices.",
    ),
    LibraryTask(
        "style-i-01",
        "Build a capsule wardrobe plan",
        "style",
        "intermediate",
        20,
        "Interchangeable pieces maximise outfit combinations.",
    ),
    LibraryTask(
        "style-i-02",
        "Experiment with layering",
        "style",
        "intermediate",
        10,
        "Layering adds visual depth and texture interest.",
    ),
    LibraryTask(
        "style-i-03",
        "Accessorise: watch, bracelet, or ring",
        "style",
        "intermediate",
        5,
        "Accessories add personality to minimal outfits.",
    ),
    LibraryTask(
        "style-i-04",
        "Study colour theory for your skin tone",
        "style",
        "intermediate",
        15,
        "Wearing your colour season enhances complexion.",
    ),
    LibraryTask(
        "style-i-05",
        "Tailor one item (hem, take in)",
        "style",
        "intermediate",
        5,
        "Tailoring transforms off-the-rack into bespoke-feeling fit.",
    ),
    LibraryTask(
        "style-a-01",
        "Create a seasonal mood board",
        "style",
        "advanced",
        20,
        "Visual planning creates intentional wardrobe evolution.",
    ),
    LibraryTask(
        "style-a-02",
        "Develop a signature scent rotation",
        "style",
        "advanced",
        10,
        "Scent becomes part of your personal brand.",
    ),
    LibraryTask(
        "style-a-03",
        "Invest in a statement piece",
        "style",
        "advanced",
        15,
        "One quality piece anchors and elevates the whole wardrobe.",
    ),
    LibraryTask(
        "style-a-04",
        "Practice monochromatic outfit styling",
        "style",
        "advanced",
        10,
        "Tonal dressing creates a sleek, intentional silhouette.",
    ),
    LibraryTask(
        "style-a-05",
        "Texture mixing: knit + leather + cotton",
        "style",
        "advanced",
        10,
        "Varied textures create visual richness without colour clutter.",
    ),
    LibraryTask(
        "style-a-06",
        "Wardrobe rotation system setup",
        "style",
        "advanced",
        15,
        "Systematic rotation ensures all pieces get worn and evaluated.",
    ),
    # =========================================================================
    # SLEEP (16 tasks)
    # =========================================================================
    LibraryTask(
        "sleep-b-01",
        "Set consistent bedtime alarm",
        "sleep",
        "beginner",
        1,
        "Anchoring bedtime regulates circadian rhythm.",
    ),
    LibraryTask(
        "sleep-b-02",
        "No screens 30 min before bed",
        "sleep",
        "beginner",
        30,
        "Blue light suppresses melatonin by up to 50%.",
    ),
    LibraryTask(
        "sleep-b-03",
        "Bedroom temperature: 18-20°C",
        "sleep",
        "beginner",
        2,
        "Cool environment triggers sleep-onset thermoregulation.",
    ),
    LibraryTask(
        "sleep-b-04",
        "No caffeine after 2 PM",
        "sleep",
        "beginner",
        1,
        "Caffeine half-life is 5-6 hours; late intake fragments sleep.",
    ),
    LibraryTask(
        "sleep-b-05",
        "Blackout curtains or sleep mask",
        "sleep",
        "beginner",
        2,
        "Complete darkness maximises melatonin production.",
    ),
    LibraryTask(
        "sleep-i-01",
        "Magnesium glycinate before bed",
        "sleep",
        "intermediate",
        1,
        "Activates GABA receptors for deeper, more restorative sleep.",
    ),
    LibraryTask(
        "sleep-i-02",
        "10-min wind-down breathing",
        "sleep",
        "intermediate",
        10,
        "4-7-8 breathing activates parasympathetic nervous system.",
    ),
    LibraryTask(
        "sleep-i-03",
        "Journal 3 things before bed",
        "sleep",
        "intermediate",
        5,
        "Offloads cognitive loops that delay sleep onset.",
    ),
    LibraryTask(
        "sleep-i-04",
        "Track sleep with app or device",
        "sleep",
        "intermediate",
        2,
        "Data awareness drives better sleep behaviour decisions.",
    ),
    LibraryTask(
        "sleep-i-05",
        "Warm shower 90 min before bed",
        "sleep",
        "intermediate",
        10,
        "Post-shower cooling mimics natural pre-sleep temperature drop.",
    ),
    LibraryTask(
        "sleep-a-01",
        "Sleep hygiene audit (full room setup)",
        "sleep",
        "advanced",
        30,
        "Optimise mattress, pillow, air quality, and noise levels.",
    ),
    LibraryTask(
        "sleep-a-02",
        "Morning sunlight within 30 min of waking",
        "sleep",
        "advanced",
        10,
        "Bright light anchors the circadian clock for better sleep timing.",
    ),
    LibraryTask(
        "sleep-a-03",
        "Progressive muscle relaxation",
        "sleep",
        "advanced",
        15,
        "Systematic tension-release reduces physiological arousal.",
    ),
    LibraryTask(
        "sleep-a-04",
        "Heart rate variability training",
        "sleep",
        "advanced",
        10,
        "Biofeedback improves autonomic balance for sleep quality.",
    ),
    LibraryTask(
        "sleep-a-05",
        "Polyphasic nap experimentation",
        "sleep",
        "advanced",
        20,
        "Strategic napping can supplement core sleep in busy schedules.",
    ),
    LibraryTask(
        "sleep-a-06",
        "Sleep restriction therapy (if needed)",
        "sleep",
        "advanced",
        1,
        "Paradoxically limiting time in bed consolidates sleep drive.",
    ),
    # =========================================================================
    # NUTRITION (18 tasks)
    # =========================================================================
    LibraryTask(
        "nutr-b-01",
        "Eat 2+ servings of vegetables",
        "nutrition",
        "beginner",
        5,
        "Micronutrient density supports skin, hair, and energy.",
    ),
    LibraryTask(
        "nutr-b-02",
        "Drink 2L water",
        "nutrition",
        "beginner",
        1,
        "Hydration supports every metabolic process.",
    ),
    LibraryTask(
        "nutr-b-03",
        "Protein with every meal",
        "nutrition",
        "beginner",
        5,
        "Amino acids are building blocks for skin, hair, and muscle.",
    ),
    LibraryTask(
        "nutr-b-04",
        "Replace one processed snack with fruit",
        "nutrition",
        "beginner",
        2,
        "Whole foods reduce inflammation and sugar spikes.",
    ),
    LibraryTask(
        "nutr-b-05",
        "Take a daily multivitamin",
        "nutrition",
        "beginner",
        1,
        "Covers micronutrient gaps in typical modern diets.",
    ),
    LibraryTask(
        "nutr-b-06",
        "No sugary drinks today",
        "nutrition",
        "beginner",
        1,
        "Liquid sugar causes insulin spikes and skin inflammation.",
    ),
    LibraryTask(
        "nutr-i-01",
        "Track macros for one day",
        "nutrition",
        "intermediate",
        10,
        "Awareness of protein/carb/fat ratio drives better choices.",
    ),
    LibraryTask(
        "nutr-i-02",
        "Eat omega-3 rich food (fish, walnuts)",
        "nutrition",
        "intermediate",
        5,
        "Anti-inflammatory fatty acids benefit skin and brain.",
    ),
    LibraryTask(
        "nutr-i-03",
        "Meal prep for 3 days",
        "nutrition",
        "intermediate",
        45,
        "Prepared meals prevent impulsive, low-quality food choices.",
    ),
    LibraryTask(
        "nutr-i-04",
        "Probiotic food (yogurt, kimchi)",
        "nutrition",
        "intermediate",
        5,
        "Gut microbiome health reflects in skin clarity.",
    ),
    LibraryTask(
        "nutr-i-05",
        "Reduce alcohol to 2 drinks max",
        "nutrition",
        "intermediate",
        1,
        "Alcohol dehydrates and impairs skin repair during sleep.",
    ),
    LibraryTask(
        "nutr-i-06",
        "Collagen peptide supplement",
        "nutrition",
        "intermediate",
        1,
        "Hydrolysed collagen supports skin elasticity and joint health.",
    ),
    LibraryTask(
        "nutr-a-01",
        "Optimise zinc and selenium intake",
        "nutrition",
        "advanced",
        5,
        "Key minerals for testosterone, hair, and immune function.",
    ),
    LibraryTask(
        "nutr-a-02",
        "Anti-inflammatory meal plan (full day)",
        "nutrition",
        "advanced",
        30,
        "Turmeric, berries, leafy greens — systematic inflammation reduction.",
    ),
    LibraryTask(
        "nutr-a-03",
        "Intermittent fasting window (16:8)",
        "nutrition",
        "advanced",
        1,
        "Time-restricted eating triggers autophagy and cellular repair.",
    ),
    LibraryTask(
        "nutr-a-04",
        "Blood work for micronutrient levels",
        "nutrition",
        "advanced",
        5,
        "Lab data replaces guesswork for targeted supplementation.",
    ),
    LibraryTask(
        "nutr-a-05",
        "Glycaemic index-aware meal planning",
        "nutrition",
        "advanced",
        15,
        "Low-GI foods stabilise insulin and reduce skin breakouts.",
    ),
    LibraryTask(
        "nutr-a-06",
        "Organ meat or superfood integration",
        "nutrition",
        "advanced",
        10,
        "Nutrient-dense foods provide concentrated micronutrient profiles.",
    ),
    # =========================================================================
    # VOICE (14 tasks)
    # =========================================================================
    LibraryTask(
        "voice-b-01",
        "Record and listen to your voice (1 min)",
        "voice",
        "beginner",
        3,
        "Self-awareness is the first step to vocal improvement.",
    ),
    LibraryTask(
        "voice-b-02",
        "Diaphragmatic breathing practice",
        "voice",
        "beginner",
        5,
        "Breath support creates a resonant, authoritative tone.",
    ),
    LibraryTask(
        "voice-b-03",
        "Humming warm-up (3 min)",
        "voice",
        "beginner",
        3,
        "Vibration warms vocal cords and finds natural resonance.",
    ),
    LibraryTask(
        "voice-b-04",
        "Read aloud for 5 minutes",
        "voice",
        "beginner",
        5,
        "Practising articulation builds clarity and confidence.",
    ),
    LibraryTask(
        "voice-b-05",
        "Drink warm water (vocal cord hydration)",
        "voice",
        "beginner",
        1,
        "Hydrated cords vibrate efficiently for a clearer tone.",
    ),
    LibraryTask(
        "voice-i-01",
        "Pitch variation exercises",
        "voice",
        "intermediate",
        10,
        "Monotone speech loses attention; variation signals engagement.",
    ),
    LibraryTask(
        "voice-i-02",
        "Pace control: slow down 20%",
        "voice",
        "intermediate",
        5,
        "Deliberate pacing projects confidence and authority.",
    ),
    LibraryTask(
        "voice-i-03",
        "Practice power pauses",
        "voice",
        "intermediate",
        5,
        "Strategic silence creates emphasis and commands attention.",
    ),
    LibraryTask(
        "voice-i-04",
        "Tongue twisters for articulation",
        "voice",
        "intermediate",
        5,
        "Rapid phoneme switching improves diction under pressure.",
    ),
    LibraryTask(
        "voice-i-05",
        "Record a 1-min monologue and review",
        "voice",
        "intermediate",
        5,
        "Iterative recording reveals filler words and weak patterns.",
    ),
    LibraryTask(
        "voice-a-01",
        "Resonance placement exercises",
        "voice",
        "advanced",
        10,
        "Shifting resonance from throat to chest creates depth.",
    ),
    LibraryTask(
        "voice-a-02",
        "Public speaking practice (5 min topic)",
        "voice",
        "advanced",
        10,
        "Structured practice builds vocal presence and confidence.",
    ),
    LibraryTask(
        "voice-a-03",
        "Vocal fry elimination drills",
        "voice",
        "advanced",
        5,
        "Removing fry improves perceived confidence and authority.",
    ),
    LibraryTask(
        "voice-a-04",
        "Mirror + camera practice session",
        "voice",
        "advanced",
        15,
        "Combining visual and vocal feedback accelerates improvement.",
    ),
]

# Quick lookup indexes
TASKS_BY_ID: dict[str, LibraryTask] = {t.id: t for t in TASK_LIBRARY}

TASKS_BY_PILLAR: dict[str, list[LibraryTask]] = {}
for _task in TASK_LIBRARY:
    TASKS_BY_PILLAR.setdefault(_task.category, []).append(_task)

TASKS_BY_PILLAR_AND_TIER: dict[tuple[str, str], list[LibraryTask]] = {}
for _task in TASK_LIBRARY:
    TASKS_BY_PILLAR_AND_TIER.setdefault((_task.category, _task.tier), []).append(_task)
